// @ts-check
import fs from 'node:fs';
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// The sidebar (table of contents) is generated from src/outline.ts by
// `npm run generate` (written to src/generated/sidebar.json). Fall back to a flat
// autogenerated list if it hasn't been generated yet.
let sidebar = [
  { label: 'Introduction', link: '/' },
  { label: 'Features', items: [{ autogenerate: { directory: 'features' } }] },
];
try {
  sidebar = JSON.parse(fs.readFileSync('./src/generated/sidebar.json', 'utf8'));
} catch {
  // sidebar.json not generated yet — keep the flat fallback.
}

// The Astro Starlight site that renders the living-documentation manual.
// Feature pages under src/content/docs/features are GENERATED from the Cucumber
// JSON by `npm run generate`; everything else here is authored.
export default defineConfig({
  integrations: [
    starlight({
      title: 'Jasper — Living Documentation',
      description:
        'The GemStone/S development environment for VS Code, documented by its own acceptance tests.',
      customCss: ['./src/styles/manual.css'],
      pagination: false,
      sidebar,
    }),
  ],
});
